// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstate.Data;

#nullable disable

namespace RealEstate.Data.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    partial class RealEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RealEstate.Entity.Concrete.EProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("eProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Backend Mahallesi",
                            AgentId = 1,
                            Area = 135m,
                            City = "İstanbul",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Adalar manzaralı, geniş ve ferah satılık daire",
                            District = "Kartal",
                            Floor = 5,
                            IsDeleted = false,
                            Price = 3250000m,
                            PropertyTypeId = 1,
                            Rooms = 3,
                            Status = 1,
                            Title = "Deniz Manzaralı 3+1 Satılık Daire",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(1420), new TimeSpan(0, 0, 0, 0, 0)),
                            YearBuilt = 2018
                        },
                        new
                        {
                            Id = 2,
                            Address = "Backend Mahallesi",
                            AgentId = 2,
                            Area = 60m,
                            City = "İstanbul",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Site içerisinde, güvenlikli kiralık daire",
                            District = "Maltepe",
                            Floor = 3,
                            IsDeleted = false,
                            Price = 18000m,
                            PropertyTypeId = 2,
                            Rooms = 1,
                            Status = 4,
                            Title = "Deniz Manzaralı 1+1 Kiralık Daire",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(6364), new TimeSpan(0, 0, 0, 0, 0)),
                            YearBuilt = 2020
                        },
                        new
                        {
                            Id = 3,
                            Address = "Villa Sokak",
                            AgentId = 2,
                            Area = 60m,
                            City = "İstanbul",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Müstakil bahçeli, havuzlu villa",
                            District = "Beykoz",
                            Floor = 3,
                            IsDeleted = false,
                            Price = 55000m,
                            PropertyTypeId = 3,
                            Rooms = 1,
                            Status = 4,
                            Title = "Bahçeli Kiralık Villa",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(6374), new TimeSpan(0, 0, 0, 0, 0)),
                            YearBuilt = 2020
                        },
                        new
                        {
                            Id = 4,
                            Address = "Çarşı Caddesi",
                            AgentId = 3,
                            Area = 60m,
                            City = "İstanbul",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Cadde üzerinde, yüksek yaya trafiği",
                            District = "Kadıköy",
                            Floor = 3,
                            IsDeleted = false,
                            Price = 6500000m,
                            PropertyTypeId = 4,
                            Rooms = 1,
                            Status = 3,
                            Title = "Merkezi Konumda Satılık Dükkan",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(6378), new TimeSpan(0, 0, 0, 0, 0)),
                            YearBuilt = 2024
                        });
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Inquiries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "SametEce@Backend.com",
                            IsDeleted = false,
                            Message = "Bu ilan hakkında bilgi almak istiyorum.",
                            Name = "Samet Ece",
                            PropertyId = 1,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(8750), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "Ece@Backend.com",
                            IsDeleted = false,
                            Message = "Kira Şartları Nedir?",
                            Name = "Ece",
                            PropertyId = 2,
                            Status = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 563, DateTimeKind.Unspecified).AddTicks(479), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("propertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DisplayOrder = 0,
                            ImageUrl = "https://example.com/property1-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            PropertyId = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(7102), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DisplayOrder = 0,
                            ImageUrl = "https://example.com/property1-2.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            PropertyId = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(8091), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DisplayOrder = 0,
                            ImageUrl = "https://example.com/property2-1.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            PropertyId = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(8093), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DisplayOrder = 0,
                            ImageUrl = "https://example.com/property2-2.jpg",
                            IsDeleted = false,
                            IsPrimary = true,
                            PropertyId = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 562, DateTimeKind.Unspecified).AddTicks(8095), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("propertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Satılık Daire ",
                            IsDeleted = false,
                            Name = "Daire",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 559, DateTimeKind.Unspecified).AddTicks(658), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Kiralık Daire",
                            IsDeleted = false,
                            Name = "Daire",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(3999), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Kiralık Villa",
                            IsDeleted = false,
                            Name = "Villa",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(4014), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Satılık Dükkan",
                            IsDeleted = false,
                            Name = "Dükkan",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(4016), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Satılık Ofis",
                            IsDeleted = false,
                            Name = "Ofis",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(4018), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Satılık Arsa",
                            IsDeleted = false,
                            Name = "Arsa",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(4020), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Kiralık İşyeri",
                            IsDeleted = false,
                            Name = "İşyeri",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 14, 10, 8, 11, 561, DateTimeKind.Unspecified).AddTicks(4022), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.EProperty", b =>
                {
                    b.HasOne("RealEstate.Entity.Concrete.PropertyType", "PropertyType")
                        .WithMany("EProperties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.Inquiry", b =>
                {
                    b.HasOne("RealEstate.Entity.Concrete.EProperty", "Property")
                        .WithMany("Inquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.PropertyImage", b =>
                {
                    b.HasOne("RealEstate.Entity.Concrete.EProperty", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.EProperty", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("RealEstate.Entity.Concrete.PropertyType", b =>
                {
                    b.Navigation("EProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
